export const languages = [
  {
    id: "html",
    label: "HTML",
    dot: "#ff8fab",
    icon: "🌐",
    title: "HTML — Structure of the Web",
    topics: [
      {
        icon: "📄",
        name: "What is HTML?",
        desc: "The skeleton of every webpage. Learn tags, elements, and structure.",
        level: "Beginner",
      },
      {
        icon: "🖼️",
        name: "Tags & Elements",
        desc: "Headings, paragraphs, images, links — the building blocks.",
        level: "Beginner",
      },
      {
        icon: "📋",
        name: "Forms & Inputs",
        desc: "Create buttons, text boxes, dropdowns, and more.",
        level: "Intermediate",
      },
      {
        icon: "🏛️",
        name: "Semantic HTML",
        desc: "Use meaningful tags like <header>, <main>, <article>.",
        level: "Intermediate",
      },
    ],
  },
  {
    id: "css",
    label: "CSS",
    dot: "#FFE066",
    icon: "🎨",
    title: "CSS — Design of the Web",
    topics: [
      {
        icon: "🌈",
        name: "Colors & Fonts",
        desc: "Make your page fabulous with colors, gradients, and fonts.",
        level: "Beginner",
      },
      {
        icon: "📐",
        name: "Flexbox",
        desc: "Align and distribute elements like a pro.",
        level: "Intermediate",
      },
      {
        icon: "🗂️",
        name: "CSS Grid",
        desc: "Build powerful two-dimensional layouts.",
        level: "Intermediate",
      },
      {
        icon: "✨",
        name: "Animations",
        desc: "Add sparkle with transitions and keyframe animations.",
        level: "Advanced",
      },
    ],
  },
  {
    id: "javascript",
    label: "JAVASCRIPT",
    dot: "#fbbf24",
    icon: "⚡",
    title: "JavaScript — Make It Interactive",
    topics: [
      {
        icon: "📚",
        name: "Variables & Types",
        desc: "Strings, numbers, booleans — data basics.",
        level: "Beginner",
      },
      {
        icon: "🔁",
        name: "Functions",
        desc: "Reusable blocks of logic that power your app.",
        level: "Beginner",
      },
      {
        icon: "🎉",
        name: "DOM Manipulation",
        desc: "Change the page dynamically with JS magic.",
        level: "Intermediate",
      },
      {
        icon: "🚀",
        name: "Async & Fetch",
        desc: "Load data from APIs and handle promises.",
        level: "Advanced",
      },
    ],
  },
  {
    id: "python",
    label: "PYTHON",
    dot: "#34d399",
    icon: "🐍",
    title: "Python — Powerful & Friendly",
    topics: [
      {
        icon: "💻",
        name: "Basics",
        desc: "Print, variables, loops — Python is easy to read!",
        level: "Beginner",
      },
      {
        icon: "📊",
        name: "Data Structures",
        desc: "Lists, dicts, sets, and tuples.",
        level: "Intermediate",
      },
      {
        icon: "🤖",
        name: "AI & ML Basics",
        desc: "Use Python for machine learning with scikit-learn.",
        level: "Advanced",
      },
      {
        icon: "📱",
        name: "Web with Flask",
        desc: "Build web apps using Python's Flask framework.",
        level: "Advanced",
      },
    ],
  },
  {
    id: "sql",
    label: "SQL",
    dot: "#60a5fa",
    icon: "🗄️",
    title: "SQL — Data is Power",
    topics: [
      {
        icon: "🔍",
        name: "SELECT Queries",
        desc: "Fetch and filter data from tables.",
        level: "Beginner",
      },
      {
        icon: "🔗",
        name: "Joins",
        desc: "Combine data from multiple tables with INNER, LEFT joins.",
        level: "Intermediate",
      },
      {
        icon: "📈",
        name: "Aggregations",
        desc: "COUNT, SUM, AVG — analyze your data.",
        level: "Intermediate",
      },
      {
        icon: "🏗️",
        name: "Database Design",
        desc: "Build schemas with primary keys, foreign keys, and indexes.",
        level: "Advanced",
      },
    ],
  },
  {
    id: "more",
    label: "MORE",
    dot: "#f472b6",
    icon: "🌟",
    title: "🌟 More Languages",
    topics: [
      {
        icon: "☕",
        name: "Java",
        desc: "Object-oriented programming with a classic language.",
        level: "Intermediate",
      },
      {
        icon: "📦",
        name: "C++",
        desc: "High-performance programming for games and systems.",
        level: "Advanced",
      },
      {
        icon: "🚀",
        name: "TypeScript",
        desc: "JavaScript with superpowers — add types for fewer bugs.",
        level: "Intermediate",
      },
      {
        icon: "🍎",
        name: "Swift",
        desc: "Create iOS and macOS apps for Apple devices.",
        level: "Intermediate",
      },
    ],
  },
];